//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criterion()
        {
            this.Mark = new HashSet<Mark>();
        }
    
        public int IdCrit { get; set; }
        public string CName { get; set; }
        public Nullable<int> CRange { get; set; }
        public Nullable<int> CWeight { get; set; }
        public string OptimType { get; set; }
        public string EdIzmer { get; set; }
        public string ScaleType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark> Mark { get; set; }
    }
}
