//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vector
    {
        public int IdVect { get; set; }
        public int IdAlt { get; set; }
        public int IdMark { get; set; }
    
        public virtual Alternative Alternative { get; set; }
        public virtual Mark Mark { get; set; }
    }
}
